### PR TITLE
Fix the Recipe Creation to have a simplier solution

### PR DESCRIPTION
**Pull request by lasododo**

### CODE REVIEW

**Comment by lasododo** [comment]
@goranek please add your review as well (@DrJekylle yours will be appriciated as well)

**Review by ArcadeArchie — CHANGES_REQUESTED** [review]
Looks good so far, but why not use a enum for Visibility?
also: 

- try to avoid inline styles in .cshtml stuff like that can be moved to a css class
- try to avoid scss based style templates since asp.net core cant do SCSS without a bundler

**Comment by lasododo** [comment]
@ArcadeArchie the visibility was not yet implemented, however I added it in, bcz I felt bad leaving there just 1 input :D

1. The reason of that inline-css is that for som unknown reason it was set to absolute and it just ended being in the middle of the screen, that one needs a bit more investigation.

2. thanks, didnt know that <3

**Comment by lasododo** [comment]
Visibility still not implemented, however, the Update and Delete are

**Review by ArcadeArchie — APPROVED** [review]
Looks good to me, just add some Method summaries for the other bois but thats just a nice to have

**Comment by lasododo** [comment]
@goranek @DrJekylle wake up .... an approval is awaiting ...

**Review by DrJekylle — APPROVED** [review]

**Review by goranek — APPROVED** [review]

**Pull request merged**
